import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, ArrowLeftRight, BarChart3, Check, CircleGauge, Cpu, History, Pause, Play, Plus, ScanLine, Settings2, Sparkles, Trash2, Zap } from "lucide-react";
import { AppFrame } from "@/components/AppFrame";
import { removeRobot, setActiveRobot, toggleRobot, useAppState, type Robot } from "@/lib/app-store";

export const Route = createFileRoute("/app/home")({
  ssr: false,
  head: () => ({ meta: [{ title: "My Robot — EA Migrate Pro" }, { name: "description", content: "Run and manage your activated trading robot." }] }),
  component: AppHome,
});

const fallbackRobotImage = "/ea-migrate-platform-robot.jpg";
function cssGlow(color: string, strength = "0 0 28px") {
  return strength + " " + color + "66";
}

function BottomHint() {
  return <p className="mt-5 text-center text-[10px] font-bold uppercase tracking-[0.22em] text-muted-foreground">Swipe through your active robot controls</p>;
}

function Powered({ color }: { color: string }) {
  return <div className="mx-auto mt-5 w-fit rounded-full border-2 bg-black/50 px-6 py-3 text-xs font-black tracking-[0.08em] text-white" style={{ borderColor: color, boxShadow: cssGlow(color) }}>Powered by <span style={{ color }}>EA Migrate</span></div>;
}

function ActionButton({ label, icon, onClick, color, active = false, className = "" }: { label: string; icon: React.ReactNode; onClick?: () => void; color: string; active?: boolean; className?: string }) {
  return <button type="button" onClick={onClick} className={"flex min-w-0 items-center justify-center gap-2 rounded-2xl border-2 px-3 py-3 text-[11px] font-black uppercase tracking-[0.06em] transition-transform active:scale-95 " + className} style={{ borderColor: color, color: active ? "#fff" : color, backgroundColor: active ? color : "rgba(0,0,0,.42)", boxShadow: cssGlow(color, "0 0 18px") }}>{icon}<span className="truncate">{label}</span></button>;
}

function CircleAction({ label, icon, onClick, color, filled = false }: { label: string; icon: React.ReactNode; onClick?: () => void; color: string; filled?: boolean }) {
  return <button type="button" onClick={onClick} className="flex size-[5.4rem] flex-col items-center justify-center gap-1 rounded-full border-4 text-[10px] font-black uppercase" style={{ borderColor: color, color: filled ? "#fff" : color, backgroundColor: filled ? color : "rgba(0,0,0,.72)", boxShadow: cssGlow(color) }}>{icon}<span>{label}</span></button>;
}

function HeroImage({ src, alt, className = "" }: { src: string; alt: string; className?: string }) {
  return <img src={src} alt={alt} className={"object-cover " + className} />;
}

function SharedRobotList({ active, robots, color }: { active: Robot; robots: Robot[]; color: string }) {
  return <section className="mt-7"><p className="text-xs font-black uppercase tracking-[0.18em] text-muted-foreground">Connected Robots</p><div className="mt-3 space-y-2">{robots.map((item) => <button type="button" key={item.id} onClick={() => setActiveRobot(item.id)} className="flex w-full items-center gap-3 rounded-full border p-2 text-left" style={{ borderColor: item.id === active.id ? color : "rgba(255,255,255,.12)", backgroundColor: item.id === active.id ? color + "22" : "rgba(255,255,255,.04)" }}><img src={item.image || fallbackRobotImage} alt="" className="size-10 rounded-full object-cover" /><span className="min-w-0 flex-1 truncate text-sm font-black uppercase">{item.name}</span>{item.id === active.id && <Check className="size-4 shrink-0" style={{ color }} />}</button>)}</div><Link to="/app/activate" className="mt-3 flex h-12 w-full items-center justify-center gap-2 rounded-full border text-xs font-black uppercase" style={{ borderColor: color, color }}><Plus className="size-4" /> Add robot</Link></section>;
}

function LayoutOrange({ active, app, color, robotName }: { active: Robot; app: ReturnType<typeof useAppState>; color: string; robotName: string }) {
  return <div className="relative overflow-hidden rounded-[2.5rem] border bg-gradient-to-b from-orange-950 via-black to-black p-5" style={{ borderColor: color, boxShadow: cssGlow(color) }}><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_28%,rgba(255,91,0,.42),transparent_36%)]" /><div className="relative text-center"><p className="text-[10px] font-black uppercase tracking-[0.24em]" style={{ color }}>EA MIGRATE PRO</p><div className="mx-auto mt-5 size-44 rounded-full border-4 bg-white p-2" style={{ borderColor: color, boxShadow: cssGlow(color) }}><HeroImage src={active.image || fallbackRobotImage} alt={robotName} className="size-full rounded-full" /></div><p className="mt-5 text-xs font-semibold text-white/70">Your Trading With</p><h1 className="mt-1 text-2xl font-black uppercase" style={{ color }}>{robotName}</h1><Powered color={color} /><div className="mt-7 grid grid-cols-3 gap-2"><CircleAction label={active.running ? "Pause" : "Start"} icon={active.running ? <Pause className="size-5" /> : <Play className="size-5" />} onClick={() => toggleRobot(active.id)} color={color} filled={active.running} /><CircleAction label="Settings" icon={<Settings2 className="size-5" />} color={color} /><CircleAction label="Migrate" icon={<ArrowLeftRight className="size-5" />} color={color} /></div><div className="mt-6 overflow-hidden rounded-[2rem] border-2 bg-white p-2" style={{ borderColor: color }}><HeroImage src={active.image || fallbackRobotImage} alt="" className="h-28 w-full rounded-[1.5rem]" /></div><SharedRobotList active={active} robots={app.robots} color={color} /><BottomHint /></div></div>;
}

function LayoutBlue({ active, app, color, robotName }: { active: Robot; app: ReturnType<typeof useAppState>; color: string; robotName: string }) {
  return <div className="relative overflow-hidden rounded-[2.5rem] border bg-gradient-to-b from-slate-950 via-black to-blue-950/50 p-5" style={{ borderColor: color, boxShadow: cssGlow(color) }}><div className="relative text-center"><p className="text-[10px] font-black uppercase tracking-[0.25em]" style={{ color }}>EA MIGRATE PRO</p><div className="mx-auto mt-5 size-44 rounded-full border-4 bg-white p-2" style={{ borderColor: color, boxShadow: cssGlow(color) }}><HeroImage src={active.image || fallbackRobotImage} alt={robotName} className="size-full rounded-full" /></div><p className="mt-5 text-xs font-semibold text-white/70">Your Trading With</p><h1 className="mt-1 text-2xl font-black uppercase" style={{ color }}>{robotName}</h1><Powered color={color} /><div className="mt-7 grid grid-cols-3 gap-2 rounded-full border-2 bg-white p-2" style={{ borderColor: color }}><ActionButton label="Pause" icon={<Pause className="size-4" />} onClick={() => active.running && toggleRobot(active.id)} color={color} className="border-0 bg-transparent text-slate-900 shadow-none" /><ActionButton label="Start" icon={<Play className="size-4" />} onClick={() => !active.running && toggleRobot(active.id)} color={color} active={!active.running} className="border-0 shadow-none" /><ActionButton label="Migrate" icon={<ArrowLeftRight className="size-4" />} color={color} className="border-0 bg-transparent text-slate-900 shadow-none" /></div><SharedRobotList active={active} robots={app.robots} color={color} /><BottomHint /></div></div>;
}

function LayoutGreen({ active, app, color, robotName }: { active: Robot; app: ReturnType<typeof useAppState>; color: string; robotName: string }) {
  return <div className="relative overflow-hidden rounded-[2.5rem] border bg-gradient-to-b from-green-950 via-emerald-950 to-black p-5" style={{ borderColor: color, boxShadow: cssGlow(color) }}><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,rgba(44,255,80,.3),transparent_45%)]" /><div className="relative text-center"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-emerald-200">EA MIGRATE PRO</p><div className="mx-auto mt-5 size-44 rounded-full border-4 bg-white p-2" style={{ borderColor: color, boxShadow: cssGlow(color) }}><HeroImage src={active.image || fallbackRobotImage} alt={robotName} className="size-full rounded-full" /></div><h1 className="mt-6 text-2xl font-black uppercase text-white">{robotName}</h1><p className="mt-1 text-xs font-semibold text-emerald-100/75">Your private trading robot</p><div className="mt-7 grid grid-cols-3 gap-2"><ActionButton label="Stop" icon={<Pause className="size-4" />} onClick={() => active.running && toggleRobot(active.id)} color={color} /><ActionButton label="Quotes" icon={<BarChart3 className="size-4" />} color={color} /><ActionButton label="Remove" icon={<Trash2 className="size-4" />} onClick={() => removeRobot(active.id)} color={color} /></div><Link to="/app/activate" className="mt-7 flex min-h-16 w-full flex-col items-center justify-center rounded-2xl text-sm font-black uppercase text-black" style={{ backgroundColor: color, boxShadow: cssGlow(color) }}><Plus className="size-5" />Add robot<span className="text-[9px] tracking-[0.12em] opacity-75">Paste license key</span></Link><SharedRobotList active={active} robots={app.robots} color={color} /><BottomHint /></div></div>;
}

function LayoutSniperCircle({ active, app, color, robotName }: { active: Robot; app: ReturnType<typeof useAppState>; color: string; robotName: string }) {
  return <div className="relative overflow-hidden rounded-[2.5rem] border bg-black p-4" style={{ borderColor: color, boxShadow: cssGlow(color) }}><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_25%,rgba(255,50,50,.34),transparent_44%)]" /><div className="relative text-center"><div className="mx-auto size-52 rounded-full border-4 p-1" style={{ borderColor: color, boxShadow: cssGlow(color) }}><HeroImage src={active.image || "/interface-sniper-circle.jpg"} alt={robotName} className="size-full rounded-full" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.2em] text-white/70">You're trading with</p><h1 className="mt-2 text-3xl font-black uppercase text-white">{robotName}</h1><Powered color={color} /><div className="mt-7 flex justify-center gap-2"><CircleAction label="Remove" icon={<Trash2 className="size-5" />} onClick={() => removeRobot(active.id)} color={color} /><CircleAction label={active.running ? "Pause" : "Start"} icon={active.running ? <Pause className="size-5" /> : <Play className="size-5" />} onClick={() => toggleRobot(active.id)} color={color} filled={!active.running} /><CircleAction label="Quotes" icon={<Activity className="size-5" />} color={color} /></div><div className="mt-7 overflow-hidden rounded-[2rem] border-4" style={{ borderColor: color }}><HeroImage src={active.image || "/interface-sniper-circle.jpg"} alt="" className="h-52 w-full" /><div className="bg-black/85 p-3 text-left text-[10px] font-black uppercase tracking-[0.18em]" style={{ color }}>● Ready</div></div><BottomHint /></div></div>;
}

function LayoutSniperFull({ active, app, color, robotName }: { active: Robot; app: ReturnType<typeof useAppState>; color: string; robotName: string }) {
  return <div className="relative overflow-hidden rounded-[2.5rem] border bg-black p-3" style={{ borderColor: color, boxShadow: cssGlow(color) }}><div className="relative overflow-hidden rounded-[2rem]" style={{ minHeight: "34rem" }}><HeroImage src={active.image || "/interface-sniper-full.jpg"} alt={robotName} className="absolute inset-0 size-full" /><div className="absolute inset-0 bg-gradient-to-b from-black/10 via-black/10 to-black" /><div className="absolute inset-x-5 bottom-7 text-center"><h1 className="text-2xl font-black uppercase text-white">{robotName}</h1><p className="mt-2 text-xs font-bold uppercase tracking-[0.2em] text-white/75">Aggressive</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-full border bg-white/10 p-2 backdrop-blur-xl" style={{ borderColor: color + "88" }}><ActionButton label="Pairs" icon={<ArrowLeftRight className="size-4" />} color={color} className="border-0 bg-transparent text-white shadow-none" /><ActionButton label={active.running ? "Stop" : "Start"} icon={active.running ? <Pause className="size-4" /> : <Play className="size-4" />} onClick={() => toggleRobot(active.id)} color={color} active={!active.running} className="border-0 shadow-none" /><ActionButton label="Logs" icon={<History className="size-4" />} color={color} className="border-0 bg-transparent text-white shadow-none" /></div><Powered color={color} /><Link to="/app/settings/scanner" className="mt-5 flex items-center gap-3 rounded-3xl border bg-white/10 p-4" style={{ borderColor: color + "66" }}><span className="flex size-11 items-center justify-center rounded-2xl text-white" style={{ backgroundColor: color }}><ScanLine className="size-5" /></span><span className="min-w-0 flex-1 text-left"><span className="block font-black text-white">AI Scanner <Sparkles className="inline size-3" style={{ color }} /></span><span className="block text-sm text-white/55">Snap a chart — get an instant signal</span></span><span className="text-xl" style={{ color }}>›</span></Link><SharedRobotList active={active} robots={app.robots} color={color} /><BottomHint /></div>;
}

function LayoutSniperVertical({ active, app, color, robotName }: { active: Robot; app: ReturnType<typeof useAppState>; color: string; robotName: string }) {
  return <div className="relative overflow-hidden rounded-[2.5rem] border bg-gradient-to-b from-slate-950 via-black to-red-950/50 p-5" style={{ borderColor: color, boxShadow: cssGlow(color) }}><div className="relative text-center"><div className="mx-auto size-44 rounded-full border-4 p-1" style={{ borderColor: color, boxShadow: cssGlow(color) }}><HeroImage src={active.image || "/interface-sniper-circle.jpg"} alt={robotName} className="size-full rounded-full" /></div><h1 className="mt-5 text-2xl font-black uppercase text-white">{robotName}</h1><div className="mt-6 flex items-center gap-3"><div className="flex flex-1 flex-col gap-2"><ActionButton label="Pairs" icon={<ArrowLeftRight className="size-4" />} color={color} /><ActionButton label={active.running ? "Pause" : "Start"} icon={active.running ? <Pause className="size-4" /> : <Play className="size-4" />} onClick={() => toggleRobot(active.id)} color={color} active={!active.running} /><ActionButton label="Logs" icon={<History className="size-4" />} color={color} /></div><div className="flex size-24 flex-col items-center justify-center rounded-3xl border-2 text-center text-[10px] font-black uppercase" style={{ borderColor: color, color, boxShadow: cssGlow(color) }}><CircleGauge className="size-7" /><span className="mt-1">AI Scan</span></div></div><Powered color={color} /><SharedRobotList active={active} robots={app.robots} color={color} /><BottomHint /></div></div>;
}

function AppHome() {
  const app = useAppState();
  const active = app.robots.find((item) => item.id === app.activeRobotId) || app.robots[0];
  const color = (typeof window !== "undefined" ? window.localStorage.getItem("themeColor") : null) || app.settings.accentColor || "#FF3B3B";
  const currentLayout = app.settings.interfaceStyle || (typeof window !== "undefined" ? window.localStorage.getItem("layout") : null) || "layout_blue";
  const robotName = active?.name || (typeof window !== "undefined" ? window.localStorage.getItem("robotName") : null) || "EA MIGRATE PRO";
  if (!active) return <AppFrame><div className="panel mt-16 p-10 text-center"><span className="mx-auto flex size-16 items-center justify-center rounded-full" style={{ backgroundColor: color + "22", color }}><Cpu className="size-8" /></span><h1 className="mt-5 text-2xl font-black uppercase">{robotName}</h1><p className="mt-2 text-sm text-muted-foreground">Add a licence key to unlock your first trading robot.</p><Link to="/app/activate" className="mt-6 flex h-14 w-full items-center justify-center gap-2 rounded-full text-sm font-black uppercase text-white" style={{ backgroundColor: color, boxShadow: cssGlow(color) }}><Plus className="size-5" /> Connect your EA</Link></div></AppFrame>;
  const props = { active, app, color, robotName };
  return <AppFrame><div className="pb-5">{currentLayout === "layout_orange" && <LayoutOrange {...props} />}{currentLayout === "layout_blue" && <LayoutBlue {...props} />}{currentLayout === "layout_green" && <LayoutGreen {...props} />}{currentLayout === "layout_sniper_circle" && <LayoutSniperCircle {...props} />}{currentLayout === "layout_sniper_full" && <LayoutSniperFull {...props} />}{currentLayout === "layout_sniper_vertical" && <LayoutSniperVertical {...props} />}{!["layout_orange", "layout_blue", "layout_green", "layout_sniper_circle", "layout_sniper_full", "layout_sniper_vertical"].includes(currentLayout) && <LayoutBlue {...props} />}</div></AppFrame>;
}
