import { MoreHorizontal, Pause, Play, Plus, ScanLine, Trash2 } from "lucide-react";
import type { InterfaceProps } from "./types";
import { robotImage } from "./types";

export function SniperClassic({ active, robots, onStart, onRemove, onSelectBot, onOpenBotModal, onOpenPairs, onOpenScanner }: InterfaceProps) {
  return <div className="min-h-screen bg-[#0A0A0A] text-white"><header className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#D32F2F]">EA MERGE</p><h1 className="text-xl font-black">{active.name}</h1></div><button type="button" onClick={onOpenBotModal} className="flex size-10 items-center justify-center rounded-full border border-white/10 bg-[#111111]"><MoreHorizontal className="size-5" /></button></header><div className="mt-6 rounded-3xl border border-[#D32F2F]/50 bg-[#111111] p-4"><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[linear-gradient(#171717_1px,transparent_1px),linear-gradient(90deg,#171717_1px,transparent_1px)] bg-[size:24px_24px] p-5"><img src={robotImage(active)} alt={active.name} className="mx-auto size-44 rounded-full object-cover" /><span className="absolute right-3 top-3 rounded-full bg-[#D32F2F] px-3 py-1 text-[10px] font-black uppercase">{active.running ? "Live" : "Ready"}</span></div><div className="mt-4 grid grid-cols-3 gap-2"><button type="button" onClick={onRemove} className="flex h-12 items-center justify-center gap-1 rounded-full border border-[#D32F2F]/60 text-xs font-black uppercase"><Trash2 className="size-4" />Remove</button><button type="button" onClick={onStart} className="flex h-12 items-center justify-center gap-1 rounded-full bg-[#D32F2F] text-xs font-black uppercase">{active.running ? <Pause className="size-4" /> : <Play className="size-4" />}{active.running ? "Stop" : "Start"}</button><button type="button" onClick={onOpenPairs} className="flex h-12 items-center justify-center gap-1 rounded-full border border-white/15 text-xs font-black uppercase">Quotes</button></div></div><InterfaceRobotList robots={robots} active={active} onSelectBot={onSelectBot} /><button type="button" onClick={onOpenScanner} className="mt-5 flex h-14 w-full items-center justify-center gap-2 rounded-2xl border border-[#D32F2F]/40 text-sm font-black uppercase text-[#ff7070]"><ScanLine className="size-5" />Chart Scanner</button></div>;
}

function InterfaceRobotList({ robots, active, onSelectBot }: Pick<InterfaceProps, "robots" | "active" | "onSelectBot">) {
  return <div className="mt-6 space-y-2">{robots.map((robot) => <button key={robot.id} type="button" onClick={() => onSelectBot(robot.id)} className={`flex w-full items-center gap-3 rounded-2xl border p-2 text-left ${robot.id === active.id ? "border-[#D32F2F] bg-[#1A1111]" : "border-white/10 bg-[#111111]"}`}><img src={robotImage(robot)} alt="" className="size-10 rounded-full object-cover" /><span className="min-w-0 flex-1 truncate text-sm font-black uppercase">{robot.name}</span><Plus className="size-4 text-white/40" /></button>)}</div>;
}
