/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardEasRouteImport } from './routes/dashboard.eas'
import { Route as DashboardLicensesRouteImport } from './routes/dashboard.licenses'
import { Route as DashboardSignalsRouteImport } from './routes/dashboard.signals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEasRoute = DashboardEasRouteImport.update({
  id: '/eas',
  path: '/eas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicensesRoute = DashboardLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignalsRoute = DashboardSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/eas': typeof DashboardEasRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/eas': typeof DashboardEasRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/eas': typeof DashboardEasRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/eas'
    | '/dashboard/licenses'
    | '/dashboard/signals'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/signin'
    | '/signup'
    | '/dashboard/eas'
    | '/dashboard/licenses'
    | '/dashboard/signals'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/eas'
    | '/dashboard/licenses'
    | '/dashboard/signals'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/eas': {
      id: '/dashboard/eas'
      path: '/eas'
      fullPath: '/dashboard/eas'
      preLoaderRoute: typeof DashboardEasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/licenses': {
      id: '/dashboard/licenses'
      path: '/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof DashboardLicensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signals': {
      id: '/dashboard/signals'
      path: '/signals'
      fullPath: '/dashboard/signals'
      preLoaderRoute: typeof DashboardSignalsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEasRoute: typeof DashboardEasRoute
  DashboardLicensesRoute: typeof DashboardLicensesRoute
  DashboardSignalsRoute: typeof DashboardSignalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEasRoute: DashboardEasRoute,
  DashboardLicensesRoute: DashboardLicensesRoute,
  DashboardSignalsRoute: DashboardSignalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
