/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivateRouteImport } from './routes/app.activate'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppMetatraderRouteImport } from './routes/app.metatrader'
import { Route as AppScannerRouteImport } from './routes/app.scanner'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardEasRouteImport } from './routes/dashboard.eas'
import { Route as DashboardLicensesRouteImport } from './routes/dashboard.licenses'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSignalsRouteImport } from './routes/dashboard.signals'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardWebsiteRouteImport } from './routes/dashboard.website'
import { Route as MentorSlugRouteImport } from './routes/mentor.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivateRoute = AppActivateRouteImport.update({
  id: '/app/activate',
  path: '/app/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMetatraderRoute = AppMetatraderRouteImport.update({
  id: '/app/metatrader',
  path: '/app/metatrader',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/app/scanner',
  path: '/app/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEasRoute = DashboardEasRouteImport.update({
  id: '/eas',
  path: '/eas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicensesRoute = DashboardLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignalsRoute = DashboardSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebsiteRoute = DashboardWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => DashboardRoute,
} as any)
const MentorSlugRoute = MentorSlugRouteImport.update({
  id: '/mentor/$slug',
  path: '/mentor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/app/activate': typeof AppActivateRoute
  '/app/home': typeof AppHomeRoute
  '/app/metatrader': typeof AppMetatraderRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/dashboard/eas': typeof DashboardEasRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/mentor/$slug': typeof MentorSlugRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/app/activate': typeof AppActivateRoute
  '/app/home': typeof AppHomeRoute
  '/app/metatrader': typeof AppMetatraderRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/dashboard/eas': typeof DashboardEasRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/mentor/$slug': typeof MentorSlugRoute
  '/app': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/app/activate': typeof AppActivateRoute
  '/app/home': typeof AppHomeRoute
  '/app/metatrader': typeof AppMetatraderRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/dashboard/eas': typeof DashboardEasRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/mentor/$slug': typeof MentorSlugRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/support'
    | '/app/activate'
    | '/app/home'
    | '/app/metatrader'
    | '/app/scanner'
    | '/app/settings'
    | '/dashboard/eas'
    | '/dashboard/licenses'
    | '/dashboard/profile'
    | '/dashboard/signals'
    | '/dashboard/stats'
    | '/dashboard/wallet'
    | '/dashboard/website'
    | '/mentor/$slug'
    | '/app/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/signin'
    | '/signup'
    | '/support'
    | '/app/activate'
    | '/app/home'
    | '/app/metatrader'
    | '/app/scanner'
    | '/app/settings'
    | '/dashboard/eas'
    | '/dashboard/licenses'
    | '/dashboard/profile'
    | '/dashboard/signals'
    | '/dashboard/stats'
    | '/dashboard/wallet'
    | '/dashboard/website'
    | '/mentor/$slug'
    | '/app'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/support'
    | '/app/activate'
    | '/app/home'
    | '/app/metatrader'
    | '/app/scanner'
    | '/app/settings'
    | '/dashboard/eas'
    | '/dashboard/licenses'
    | '/dashboard/profile'
    | '/dashboard/signals'
    | '/dashboard/stats'
    | '/dashboard/wallet'
    | '/dashboard/website'
    | '/mentor/$slug'
    | '/app/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  AppActivateRoute: typeof AppActivateRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMetatraderRoute: typeof AppMetatraderRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  MentorSlugRoute: typeof MentorSlugRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/activate': {
      id: '/app/activate'
      path: '/app/activate'
      fullPath: '/app/activate'
      preLoaderRoute: typeof AppActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/metatrader': {
      id: '/app/metatrader'
      path: '/app/metatrader'
      fullPath: '/app/metatrader'
      preLoaderRoute: typeof AppMetatraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/scanner': {
      id: '/app/scanner'
      path: '/app/scanner'
      fullPath: '/app/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/eas': {
      id: '/dashboard/eas'
      path: '/eas'
      fullPath: '/dashboard/eas'
      preLoaderRoute: typeof DashboardEasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/licenses': {
      id: '/dashboard/licenses'
      path: '/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof DashboardLicensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signals': {
      id: '/dashboard/signals'
      path: '/signals'
      fullPath: '/dashboard/signals'
      preLoaderRoute: typeof DashboardSignalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/website': {
      id: '/dashboard/website'
      path: '/website'
      fullPath: '/dashboard/website'
      preLoaderRoute: typeof DashboardWebsiteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/mentor/$slug': {
      id: '/mentor/$slug'
      path: '/mentor/$slug'
      fullPath: '/mentor/$slug'
      preLoaderRoute: typeof MentorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardEasRoute: typeof DashboardEasRoute
  DashboardLicensesRoute: typeof DashboardLicensesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSignalsRoute: typeof DashboardSignalsRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWebsiteRoute: typeof DashboardWebsiteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEasRoute: DashboardEasRoute,
  DashboardLicensesRoute: DashboardLicensesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSignalsRoute: DashboardSignalsRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWebsiteRoute: DashboardWebsiteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  AppActivateRoute: AppActivateRoute,
  AppHomeRoute: AppHomeRoute,
  AppMetatraderRoute: AppMetatraderRoute,
  AppScannerRoute: AppScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  MentorSlugRoute: MentorSlugRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
