/**
 * POST /api/trade-notify — called by the MQL5 EA (WebRequest) and by any
 * bridge that executes a trade.
 *
 * Body: { secret, email, symbol, action, volume, price, profit, ticket }
 * `secret` must equal TRADE_WEBHOOK_SECRET (env, generated by the owner).
 *
 * Flow: verify secret → insert trade_notifications → read every device_token
 * for the email → FCM push each:
 *   title  "Trade Executed: BUY EURUSD"
 *   body   "0.10 lot @ 1.0850 | Profit $2.30"
 *   data   { symbol, action }
 * A push failure never fails the webhook — the trade row is the record.
 */
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { fcmConfigured, sendPush } from "../src/lib/fcm.server.js";

type ApiRequest = { method?: string; body?: unknown };
type ApiResponse = {
  status(code: number): ApiResponse;
  json(body: unknown): void;
  setHeader(key: string, value: string): void;
};

function body(request: ApiRequest): Record<string, unknown> {
  if (typeof request.body === "string") {
    try {
      return JSON.parse(request.body) as Record<string, unknown>;
    } catch {
      return {};
    }
  }
  return (request.body ?? {}) as Record<string, unknown>;
}

function db(): SupabaseClient | null {
  const url = (process.env["SUPABASE_URL"] ?? process.env["VITE_SUPABASE_URL"] ?? "").trim();
  const serviceRole = (process.env["SUPABASE_SERVICE_ROLE_KEY"] ?? "").trim();
  if (!url || !serviceRole) return null;
  return createClient(url, serviceRole, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export default async function handler(request: ApiRequest, response: ApiResponse): Promise<void> {
  if (request.method !== "POST") {
    response.setHeader("Allow", "POST");
    response.status(405).json({ ok: false, error: "Method not allowed" });
    return;
  }
  const input = body(request);
  const secret = (process.env["TRADE_WEBHOOK_SECRET"] ?? "").trim();
  if (!secret) {
    response.status(503).json({ ok: false, error: "TRADE_WEBHOOK_SECRET is not set on the server" });
    return;
  }
  // Constant-shape compare; an empty or wrong secret is refused before any write.
  const provided = String(input["secret"] ?? "");
  if (provided !== secret) {
    response.status(401).json({ ok: false, error: "Invalid secret" });
    return;
  }
  const email = String(input["email"] ?? "").trim().toLowerCase();
  const symbol = String(input["symbol"] ?? "").trim().toUpperCase();
  const action = String(input["action"] ?? "").trim().toUpperCase();
  if (!email || !symbol || !["BUY", "SELL", "CLOSE"].includes(action)) {
    response.status(400).json({ ok: false, error: "email, symbol and action (BUY/SELL/CLOSE) are required" });
    return;
  }
  const volume = Number(input["volume"]) || 0;
  const price = Number(input["price"]) || 0;
  const profit = Number(input["profit"]) || 0;
  const ticket = String(input["ticket"] ?? "").trim();

  const client = db();
  if (!client) {
    response.status(503).json({ ok: false, error: "Notification storage is not configured" });
    return;
  }

  // 1. THE TRADE ROW — the durable record, written before any push attempt.
  const { error: insertError } = await client.from("trade_notifications").insert({
    email,
    symbol,
    action,
    volume,
    price,
    profit,
  });
  if (insertError) {
    console.error("[trade-notify] insert failed:", insertError.message);
    response.status(500).json({ ok: false, error: "Could not record the trade" });
    return;
  }

  // 2. FAN OUT — every device registered for this email.
  const title = `Trade Executed: ${action} ${symbol}`;
  const priceText = price % 1 === 0 ? price.toFixed(0) : price.toFixed(4);
  const bodyText = `${volume.toFixed(2)} lot @ ${priceText} | Profit $${profit.toFixed(2)}`;
  const data = { symbol, action, ...(ticket ? { ticket } : {}) };

  let tokens: string[] = [];
  const { data: rows, error: tokenError } = await client
    .from("device_tokens")
    .select("fcm_token")
    .eq("email", email);
  if (tokenError) {
    console.error("[trade-notify] token lookup failed:", tokenError.message);
  } else {
    tokens = (rows ?? []).map((row) => String((row as { fcm_token?: unknown }).fcm_token ?? "")).filter(Boolean);
  }

  let sent = 0;
  const failures: string[] = [];
  if (tokens.length === 0) {
    failures.push("no device registered for this email");
  } else if (!fcmConfigured()) {
    failures.push("FIREBASE_SERVICE_ACCOUNT_JSON not set");
  } else {
    for (const token of tokens) {
      const result = await sendPush(token, title, bodyText, data);
      if (result.ok) sent += 1;
      else failures.push(result.error.slice(0, 160));
    }
  }

  // The webhook always answers 200 once the trade is recorded: an MQL5
  // WebRequest retry must not duplicate the trade row over a dead push path.
  response.status(200).json({ ok: true, stored: true, pushed: sent, tokens: tokens.length, failures });
}
